trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'acrdps.azurecr.io/dps/dpsapi'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.0.x' # Use the appropriate .NET 9 version
        installationPath: $(Agent.ToolsDirectory)/dotnet
        includePreviewVersions: true

    - script: |
        dotnet build --configuration Release
      displayName: 'Build project'

    - script: |
        dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish project'

    - task: Docker@2
      displayName: Login in ACR
      inputs:
        command: login
        containerRegistry: 'dps-acr-connection'

    - task: Docker@2
      inputs:
        containerRegistry: 'dps-acr-connection' # Define this in your Azure DevOps project
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(Build.BuildId)
